mercure:
    hubs:
        default:
            url: '%env(MERCURE_BASE_URL)%/.well-known/mercure'
            public_url: '%env(PUBLIC_URL)%/.well-known/mercure'
            jwt:
                secret: '%env(MERCURE_PUBLISHER_JWT_KEY)%'
                publish: '*'
